apiVersion: v1
kind: Service
metadata:
  name: board-frontend-service
  namespace: board-app
  labels:
    app: board-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: board-frontend 