apiVersion: v1
kind: Service
metadata:
  name: PROJECT_NAME-backend-service
  namespace: board-app
  labels:
    app: PROJECT_NAME-backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: PROJECT_NAME-backend 